# Generated by Django 4.0.4 on 2022-06-02 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='GoodItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='Дата поступления')),
                ('title', models.CharField(max_length=255, verbose_name='Название товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Цена')),
                ('unit', models.PositiveIntegerField(choices=[(1, 'шт.'), (2, 'кг.')], verbose_name='Еденица измерения')),
                ('slug', models.SlugField(max_length=255)),
                ('supplier', models.CharField(max_length=255, verbose_name='Имя поставщика')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='goods_app.category')),
            ],
            options={
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
