# Generated by Django 4.0.4 on 2022-05-29 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='Дата поступления')),
                ('title', models.CharField(max_length=255, verbose_name='Название товара')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена')),
                ('unit', models.PositiveIntegerField(choices=[(1, 'шт.'), (2, 'кг.')], verbose_name='Еденица измерения')),
                ('supplier', models.CharField(max_length=255, verbose_name='Имя поставщика')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
